## Based on https://github.com/scaleway/ultraviolet/blob/7ba5ded00462e30d5a37de90c06be49640786849/.github/workflows/changesets-renovate.yml

name: Generate changeset for Renovate

on:
  pull_request_target:
    paths:
      - ".github/workflows/changesets-renovate.yml"
      - "**/pnpm-lock.yaml"
      - "**/package.json"

jobs:
  generate-changeset:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]' && github.repository == 'Arbeidstilsynet/design'
    steps:
      - name: Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2
        with:
          app-id: ${{ vars.BETZY_BOT_APP_ID }}
          private-key: ${{ secrets.BETZY_BOT_PRIVATE_KEY }}

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 10
          ref: ${{ github.head_ref }}
          token: ${{ steps.app-token.outputs.token }}

      - name: Set git user
        run: |
          git config --global user.name "${{ vars.BETZY_BOT_GIT_USER_NAME }}"
          git config --global user.email "${{ vars.BETZY_BOT_GIT_USER_EMAIL }}"

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 24
          cache: "pnpm"

      - name: Run changesets-renovate
        run: pnpm dlx @scaleway/changesets-renovate
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
