name: Generate CSS from Figma tokens

on:
  push:
    branches-ignore:
      - "main"
      - "renovate/**"
      - "changeset-release/**"
    paths:
      - "design-tokens/**"
      - "!design-tokens/README.md"
      - "package.json" # run on updates to Digdir CLI, needs better handling?
      - ".github/workflows/generate-tokens.yml"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build-css:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: Arbeidstilsynet/action-pnpm-setup@f3d97993013e8b1a22061064fbc5786b3a84bfd6 # v1

      - name: Generate CSS
        run: pnpm tokens:build

      - name: Commit changes
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        with:
          pull: "--rebase --autostash"
          default_author: github_actions
          message: "Generated theme CSS"
          add: "."
