name: Generate CSS from Figma tokens

on:
  push:
    branches-ignore:
      - "main"
      - "renovate/**"
      - "changeset-release/**"
    paths:
      - "design-tokens/**"
      - "!design-tokens/README.md"
      - "package.json" # run on updates to Digdir CLI, needs better handling?
      - ".github/workflows/generate-tokens.yml"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build-css:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: Arbeidstilsynet/action-pnpm-setup@549a790d028b3270d8249e47943fd1a5fadcd2f8 # v1

      - name: Generate CSS
        run: pnpm tokens:build

      - name: Commit changes
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        with:
          pull: "--rebase --autostash"
          default_author: github_actions
          message: "Generated theme CSS"
          add: "."
