name: Storybook tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./apps/storybook
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: Arbeidstilsynet/action-pnpm-setup@549a790d028b3270d8249e47943fd1a5fadcd2f8 # v1
      - run: pnpm exec playwright install
      - name: Build CSS
        run: pnpm --filter @arbeidstilsynet/design-css build
      - run: pnpm test
